# Site settings
title: "Arigala Adarsh Portfolio"
description: "Portfolio site of Arigala Adarsh"
url: "https://arigalaadarsh.github.io" # your GitHub Pages site URL
baseurl: "/portfolio"                  # the subpath (important for repo not at root)

# Build settings
markdown: kramdown
theme: jekyll-theme-primer             # choose your theme
plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout

# Collections
collections:
  publications:
    output: true
  news:
    output: true
  certifications:
    output: true
  volunteering:
    output: true
  gallery:
    output: true

# Optional: exclude files/folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md

# Optional: timezone
timezone: Asia/Kolkata
